# Generated by Django 5.2.5 on 2026-03-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files_api", "0002_extractionresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
