# Generated by Django 5.2.5 on 2026-04-16 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("role", models.CharField(max_length=200)),
                ("department", models.CharField(blank=True, max_length=200)),
                ("expertise_tags", models.JSONField(default=list)),
                ("slack_handle", models.CharField(blank=True, max_length=100)),
                (
                    "preferred_channel",
                    models.CharField(
                        choices=[("email", "Email"), ("slack", "Slack")],
                        default="email",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("allow_automated", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="added_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
                "unique_together": {("workspace_owner", "email")},
            },
        ),
    ]
