# Generated by Django 5.2.5 on 2026-04-16 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bom_agent", "0001_initial"),
        ("files_api", "0004_fileembedding"),
        ("projects", "0002_exportlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BomResearchRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("gathering_inputs", "Gathering Inputs"),
                            ("researching", "Researching"),
                            ("generating_report", "Generating Report"),
                            ("awaiting_team_input", "Awaiting Team Input"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="gathering_inputs",
                        max_length=30,
                    ),
                ),
                ("inputs_json", models.JSONField(default=dict)),
                ("research_log", models.JSONField(default=list)),
                ("results_json", models.JSONField(default=dict)),
                ("excel_s3_key", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_runs",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BomLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_name", models.CharField(max_length=300)),
                ("part_number", models.CharField(blank=True, max_length=100)),
                ("material_spec", models.CharField(blank=True, max_length=300)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("researching", "Researching"),
                            ("sourced", "Sourced"),
                            ("needs_input", "Needs Input"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bom_line_items",
                        to="files_api.uploadedfile",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="bom_agent.bomresearchrun",
                    ),
                ),
            ],
            options={
                "ordering": ["part_name"],
            },
        ),
        migrations.CreateModel(
            name="SupplierQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier_name", models.CharField(max_length=200)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("moq", models.IntegerField()),
                ("lead_time_days", models.IntegerField()),
                (
                    "tooling_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("source_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("is_selected", models.BooleanField(default=False)),
                (
                    "line_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="bom_agent.bomlineitem",
                    ),
                ),
            ],
        ),
    ]
