# Generated by Django 5.2.5 on 2026-04-16 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bom_agent", "0002_bomresearchrun_bomlineitem_supplierquote"),
        ("files_api", "0004_fileembedding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                (
                    "doc_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("avl", "Approved Vendor List"),
                            ("material-spec", "Material Specification"),
                            ("compliance", "Compliance Document"),
                            ("previous-bom", "Previous BOM"),
                            ("scorecard", "Supplier Scorecard"),
                            ("standard", "Design Standard"),
                            ("preferred-materials", "Preferred Materials"),
                        ],
                        max_length=30,
                    ),
                ),
                ("s3_key", models.CharField(max_length=500, unique=True)),
                ("file_size", models.BigIntegerField()),
                ("file_type", models.CharField(blank=True, max_length=50)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="library_versions",
                        to="files_api.uploadedfile",
                    ),
                ),
                (
                    "workspace_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="library_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="bomresearchrun",
            name="library_documents",
            field=models.ManyToManyField(
                blank=True, related_name="bom_runs", to="bom_agent.librarydocument"
            ),
        ),
        migrations.CreateModel(
            name="LibraryEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embedding_json", models.JSONField()),
                ("doc_type", models.CharField(blank=True, max_length=30)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="bom_agent.librarydocument",
                    ),
                ),
            ],
        ),
    ]
