# Generated by Django 5.2.5 on 2026-04-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom_agent', '0003_librarydocument_bomresearchrun_library_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierquote',
            name='is_avl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='landed_cost_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
