# Generated by Django 5.2.5 on 2026-04-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom_agent', '0004_supplierquote_is_avl_landed_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarydocument',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
    ]
