# Generated by Django 5.2.5 on 2026-04-20 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom_agent', '0005_librarydocument_extracted_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(max_length=200)),
                ('question', models.TextField()),
                ('channel', models.CharField(choices=[('email', 'Email'), ('slack', 'Slack')], default='email', max_length=10)),
                ('email_subject', models.CharField(blank=True, max_length=500)),
                ('email_body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('sent', 'Sent'), ('answered', 'Answered'), ('follow_up', 'Follow-up Sent')], default='draft', max_length=20)),
                ('response', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_requests', to='bom_agent.teamcontact')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_requests', to='bom_agent.bomresearchrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
