# Generated by Django 5.2.5 on 2026-04-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom_agent', '0007_teamrequest_gmail_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
