# Generated by Django 5.2.5 on 2026-09-27 18:00

from django.db import migrations, models


def backfill_ingest_status(apps, schema_editor):
    # Docs ingested by the old daemon threads either got an embedding or failed
    # silently; there is no in-flight state to preserve.
    LibraryDocument = apps.get_model("bom_agent", "LibraryDocument")
    LibraryDocument.objects.filter(embedding__isnull=False).update(ingest_status="ready")
    LibraryDocument.objects.filter(embedding__isnull=True).update(ingest_status="failed")


class Migration(migrations.Migration):

    dependencies = [
        ('bom_agent', '0008_teamrequest_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomresearchrun',
            name='job_token',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='librarydocument',
            name='ingest_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.RunPython(backfill_ingest_status, migrations.RunPython.noop),
    ]
